---
# MIT License
# Copyright (c) 2017 Nicola Worthington <nicolaw@tfb.net>

# https://docs.docker.com/compose/compose-file

version: "3"
services:
  mariadb:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-okgreat}"
      MYSQL_USER: "${DB_USERNAME:-trinity}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-trinity}"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      timeout: "20s"
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - ../../artifacts/mysql:/var/lib/mysql
      - ../../artifacts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  authserver:
    build: ../authserver
    environment:
      DB_HOST: "${DB_HOST:-mariadb}"
      DB_PORT: "${DB_PORT:-3306}"
    depends_on:
      - mariadb
    links:
      - mariadb:mysql
    ports:
      - "3724:3724"
    volumes:
      - ../../artifacts/etc:/opt/trinitycore/etc
  worldserver:
    build: ../worldserver
    environment:
      DB_HOST: "${DB_HOST:-mariadb}"
      DB_PORT: "${DB_PORT:-3306}"
    depends_on:
      - mariadb
    links:
      - mariadb:mysql
    ports:
      - "8085:8085"
      - "3443:3443"
      - "7878:7878"
    volumes:
      - ../../artifacts/etc:/opt/trinitycore/etc
      - ../../artifacts/mapdata:/opt/trinitycore/mapdata
      - ../../artifacts/sql:/opt/trinitycore/sql
  tcjsonapi:
    build: ../tcjsonapi
    environment:
      DB_HOST: "${DB_HOST:-mariadb}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_USERNAME: "${DB_USERNAME:-trinity}"
      DB_PASSWORD: "${DB_PASSWORD:-trinity}"
      BIND_IP: "0.0.0.0"
      BIND_PORT: "80"
    depends_on:
      - mariadb
    links:
      - mariadb:mysql
    ports:
      - "8081:80"
  keira2:
    build: ../keira2
    environment:
      TC_JSON_API_PORT: "8081"
      #TC_JSON_API_URL: "location.protocol + '//' + location.hostname + ':' + '${TC_JSON_API_PORT}' + '/public/index.php/'"
    depends_on:
      - tcjsonapi
    ports:
      - "8082:80"
#
# TODO: aowow is still a work in progress.
#
#  aowow:
#    build: ../aowow
#    environment:
#      DB_HOST: "${DB_HOST:-mariadb}"
#      DB_USERNAME: "${DB_USERNAME:-trinity}"
#      DB_PASSWORD: "${DB_USERNAME:-trinity}"
#      DB_AOWOW: "${DB_AOWOW:-aowow}"
#    volumes:
#      - ../../artifacts/mpqdata:/usr/local/aowow/setup/mpqdata
#      - ../../World_of_Warcraft:/usr/local/World_of_Warcraft:ro
#    depends_on:
#      - mariadb
#    links:
#      - mariadb:mysql
#    ports:
#      - "8083:80"
