version: "3"
services:
  authserver:
    build: ../authserver
    depends_on:
      - mariadb
    links:
      - mariadb:mysql
    ports:
      - "3724:3724"
    volumes:
      - ../../artifacts/etc:/opt/trinitycore/etc
  worldserver:
    build: ../worldserver
    depends_on:
      - mariadb
    links:
      - mariadb:mysql
    ports:
      - "8085:8085"
      - "3443:3443"
      - "7878:7878"
    volumes:
      - ../../artifacts/etc:/opt/trinitycore/etc
      - ../../artifacts/mapdata:/opt/trinitycore/mapdata
      - ../../artifacts/sql:/opt/trinitycore/sql
  mariadb:
    image: "mariadb:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=okgreat
      - MYSQL_USER=trinity
      - MYSQL_PASSWORD=trinity
    ports:
      - "3307:3306"
    volumes:
      - ../../artifacts/mysql:/var/lib/mysql
      - ../../artifacts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
